name: Maven Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: smart-pos-dependency
        settings-path: ${{ github.workspace }}

    - name: Configure Maven settings for GitHub Packages
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: smart-pos-dependency
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        settings-path: ${{ github.workspace }}/settings.xml

    - name: Update version
      run: |
        # Get the current version from pom.xml
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -s ${{ github.workspace }}/settings.xml)
        echo "Current version: $CURRENT_VERSION"

        # Split the version into major, minor, and patch
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
        MAJOR="${VERSION_PARTS[0]}"
        MINOR="${VERSION_PARTS[1]}"
        PATCH="${VERSION_PARTS[2]}"

        # Increment the patch version
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "New version: $NEW_VERSION"

        # Update the version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false -s ${{ github.workspace }}/settings.xml

        # Configure Git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Commit and push the version update
        git add pom.xml
        git commit -m "Bump version to $NEW_VERSION [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn deploy -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
